//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gP2os.Participants.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResMessage() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gP2os.Participant.Localization.ResMessage", typeof(ResMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string msgCheckCredential
        {
            get
            {
                return ResourceManager.GetString("msgCheckCredential", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro não pôde ser salvo..
        /// </summary>
        public static string msgCannotSaveRecord {
            get {
                return ResourceManager.GetString("msgCannotSaveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação.
        /// </summary>
        public static string msgConfirmTitle {
            get {
                return ResourceManager.GetString("msgConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirma a remoção deste registro?.
        /// </summary>
        public static string msgDeleteConfirmation {
            get {
                return ResourceManager.GetString("msgDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não há registro para mostrar..
        /// </summary>
        public static string msgNoRecord {
            get {
                return ResourceManager.GetString("msgNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível excluir este registro..
        /// </summary>
        public static string msgNotDeleted {
            get {
                return ResourceManager.GetString("msgNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro já disponível.
        /// </summary>
        public static string msgRecordAvailable {
            get {
                return ResourceManager.GetString("msgRecordAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro não está mais disponível.
        /// </summary>
        public static string msgRecordUnavailable {
            get {
                return ResourceManager.GetString("msgRecordUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro alterado por outro usuário. Recarregue-o antes de alterar..
        /// </summary>
        public static string msgReloadRecord {
            get {
                return ResourceManager.GetString("msgReloadRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este campo é obrigatório..
        /// </summary>
        public static string msgRequiredField {
            get {
                return ResourceManager.GetString("msgRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisa por conteúdo.
        /// </summary>
        public static string msgSearchOnFields {
            get {
                return ResourceManager.GetString("msgSearchOnFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inclui.
        /// </summary>
        public static string wrdAdd {
            get {
                return ResourceManager.GetString("wrdAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filiação: Nome da Mãe.
        /// </summary>
        public static string wrdAffiliarionMother {
            get {
                return ResourceManager.GetString("wrdAffiliarionMother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Nacimento.
        /// </summary>
        public static string wrdBirthDate {
            get {
                return ResourceManager.GetString("wrdBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancela.
        /// </summary>
        public static string wrdCancel {
            get {
                return ResourceManager.GetString("wrdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecionar.
        /// </summary>
        public static string wrdChoose {
            get {
                return ResourceManager.GetString("wrdChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solicitando Confirmação..
        /// </summary>
        public static string wrdConfirmTitle {
            get {
                return ResourceManager.GetString("wrdConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove.
        /// </summary>
        public static string wrdDelete {
            get {
                return ResourceManager.GetString("wrdDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edita.
        /// </summary>
        public static string wrdEdit {
            get {
                return ResourceManager.GetString("wrdEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exporta.
        /// </summary>
        public static string wrdExport {
            get {
                return ResourceManager.GetString("wrdExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Primeiro Nome.
        /// </summary>
        public static string wrdFirstName {
            get {
                return ResourceManager.GetString("wrdFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a gP2os.
        /// </summary>
        public static string wrdgP2os {
            get {
                return ResourceManager.GetString("wrdgP2os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        public static string wrdID {
            get {
                return ResourceManager.GetString("wrdID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Incorporação.
        /// </summary>
        public static string wrdIncorporationDate {
            get {
                return ResourceManager.GetString("wrdIncorporationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro Novo.
        /// </summary>
        public static string wrdInsertingRecord {
            get {
                return ResourceManager.GetString("wrdInsertingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocupação Princial.
        /// </summary>
        public static string wrdMainOccupation {
            get {
                return ResourceManager.GetString("wrdMainOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contribuição Mensal.
        /// </summary>
        public static string wrdMonthlyIncome {
            get {
                return ResourceManager.GetString("wrdMonthlyIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string wrdName {
            get {
                return ResourceManager.GetString("wrdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ok.
        /// </summary>
        public static string wrdOk {
            get {
                return ResourceManager.GetString("wrdOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PPE.
        /// </summary>
        public static string wrdPEP {
            get {
                return ResourceManager.GetString("wrdPEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PPE - Motivo.
        /// </summary>
        public static string wrdPEPReason {
            get {
                return ResourceManager.GetString("wrdPEPReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        public static string wrdPhone {
            get {
                return ResourceManager.GetString("wrdPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foto.
        /// </summary>
        public static string wrdPhoto {
            get {
                return ResourceManager.GetString("wrdPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Prever Relatório.
        /// </summary>
        public static string wrdPreviewReport {
            get {
                return ResourceManager.GetString("wrdPreviewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imprime.
        /// </summary>
        public static string wrdPrint {
            get {
                return ResourceManager.GetString("wrdPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Celular Pessoal.
        /// </summary>
        public static string wrdPrivatePhone {
            get {
                return ResourceManager.GetString("wrdPrivatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro.
        /// </summary>
        public static string wrdRecord {
            get {
                return ResourceManager.GetString("wrdRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conteúdo do Registro.
        /// </summary>
        public static string wrdRecordContents {
            get {
                return ResourceManager.GetString("wrdRecordContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Referência.
        /// </summary>
        public static string wrdReference {
            get {
                return ResourceManager.GetString("wrdReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recarregar.
        /// </summary>
        public static string wrdReload {
            get {
                return ResourceManager.GetString("wrdReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Relatório.
        /// </summary>
        public static string wrdReport {
            get {
                return ResourceManager.GetString("wrdReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Retorno.
        /// </summary>
        public static string wrdReturn {
            get {
                return ResourceManager.GetString("wrdReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salva.
        /// </summary>
        public static string wrdSave {
            get {
                return ResourceManager.GetString("wrdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvo.
        /// </summary>
        public static string wrdSaved {
            get {
                return ResourceManager.GetString("wrdSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Busca....
        /// </summary>
        public static string wrdSearchDot {
            get {
                return ResourceManager.GetString("wrdSearchDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobrenome.
        /// </summary>
        public static string wrdSurename {
            get {
                return ResourceManager.GetString("wrdSurename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título/Descrição.
        /// </summary>
        public static string wrdTitle {
            get {
                return ResourceManager.GetString("wrdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualizando Registro.
        /// </summary>
        public static string wrdUpdatingRecord {
            get {
                return ResourceManager.GetString("wrdUpdatingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aguarde.
        /// </summary>
        public static string wrdWait {
            get {
                return ResourceManager.GetString("wrdWait", resourceCulture);
            }
        }
    }
}
